petshop/urls.py
from django.contrib import admin
from django.urls import path, include

from base.views import inicio
from base.views import contato
from base.views import reservaDeBanho

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', inicio),
    path('contato/', contato),
    path('reserva-de-banho', reservaDeBanho),
    path('reserva/', include('reserva.urls', namespace='reserva')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('rest_api.urls', namespace='api'))
]

reserva/urls.py
from django.urls import path

from reserva.views import criar_reserva

app_name = 'reserva'

urlpatterns = [
  path('criar/', criar_reserva, name='criar_reserva'),
]

rest_api/urls.py
from django.urls import path

from rest_framework.routers import SimpleRouter

from rest_api.views import hello_world, AgendamentoModelViewSet, ContatoModelViewSet, PetshopModelViewSet

app_name = 'rest_api'

router = SimpleRouter()
router.register('agendamento', AgendamentoModelViewSet)
router.register('contato', ContatoModelViewSet)
router.register('petshop', PetshopModelViewSet)

urlpatterns = [
  path('hello-world', hello_world, name='api-hello-world')
]

urlpatterns += router.urls

base/models.py
from django.db import models

class Contato(models.Model):
  nome = models.CharField(max_length=50)
  email = models.EmailField(max_length=75)
  mensagem = models.TextField()
  data = models.DateTimeField(auto_now_add=True)
  lido = models.BooleanField(default=False, blank=True)

  def __str__(self):
    return f'Nome: {self.nome} - Email: {self.email}'
  
  class Meta:
    verbose_name = 'Formulário de Contato'
    verbose_name_plural = 'Formulário de Contatos'
    ordering = ['-nome']


class ReservaDeBanho(models.Model):
  nomeDoPet = models.CharField(max_length=50)
  telefone = models.CharField(max_length=15)
  diaDaReserva = models.DateField()
  observacoes = models.TextField(blank=True)

reserva/models.py
from django.db import models

# Create your models here.
class Reserva(models.Model):
  TAMANHO_OPCOES = (
    (0, 'Pequeno'),
    (1, 'Médio'),
    (2, 'Grande')
  )

  TURNO_OPCOES = (
    ('manha', 'Manhã'),
    ('tarde', 'Tarde')
  )

  nomeDoPet = models.CharField(verbose_name='Nome do PET', max_length=50)
  nomeDoDono = models.CharField(verbose_name='Nome do Dono', max_length=50)
  telefone = models.CharField(verbose_name='Telefone', max_length=15)
  data = models.DateField(verbose_name='Data')
  observacoes = models.TextField(verbose_name='Observações', blank=True)
  tamanho = models.IntegerField(verbose_name='Tamanho', choices=TAMANHO_OPCOES)
  turno = models.CharField(verbose_name='Turno', max_length=10, choices=TURNO_OPCOES)
  petshop = models.ForeignKey(
    'Petshop',
    related_name = 'reservas',
    on_delete = models.CASCADE,
    blank = True,
    null = True
  )

  def __str__(self):
    return f'Dono: {self.nomeDoDono} - PET: {self.nomeDoPet} - Data da reserva: {self.data} - Turno: {self.turno}'

  class Meta:
    verbose_name = 'Reserva de Banho'
    verbose_name_plural = 'Reservas de Banhos'

class Petshop(models.Model):
  nome = models.CharField(verbose_name = 'Nome', max_length = 50)
  rua = models.CharField(verbose_name = 'Rua', max_length = 100)
  numero = models.CharField(verbose_name = 'Número', max_length = 10)
  bairro = models.CharField(verbose_name = 'Bairro', max_length = 50)

  def __str__(self):
    return f'Nome: {self.nome} - {self.rua}, {self.numero} - {self.bairro}'
  
  def qtd_reservas(self):
    return self.reservas.count()
  

rest_api/models.py
from django.db import models

# Create your models here.

base/forms.py
from django import forms
from base.models import Contato
from base.models import ReservaDeBanho

class ContatoForm(forms.ModelForm):
  class Meta:
    model = Contato
    fields = ['nome', 'email', 'mensagem']

class ReservaDeBanhoForm(forms.ModelForm):
  class Meta:
    model = ReservaDeBanho
    fields = ['nomeDoPet', 'telefone', 'diaDaReserva', 'observacoes']
    labels = {
      'nomeDoPet': 'Nome do PET',
      'diaDaReserva': 'Dia da reserva',
      'observacoes': 'Observações'
    }
    widgets = {
      'diaDaReserva': forms.DateInput(attrs={'type': 'date'}),
    }
  

reserva/forms.py
from reserva.models import Reserva
from django import forms
from datetime import date

class ReservaForm(forms.ModelForm):
  class Meta:
    model = Reserva
    fields = '__all__'

    widgets = {
      'data': forms.DateInput(attrs={'type': 'date'}),
    }

  def clean_data(self):
    data = self.cleaned_data['data']
    hoje = date.today()

    if data < hoje:
      raise forms.ValidationError('Não é possível reservar um banho para uma data do passado!')
    
    quantidadeAtualDeReservas = Reserva.objects.filter(data=data).count()
    print(f'quantidade: {quantidadeAtualDeReservas}')

    if quantidadeAtualDeReservas >= 4:
      raise forms.ValidationError('O dia selecionado já está lotado. Selecione outro dia para a sua reserva!')

    return data

base/views.py
from django.shortcuts import render
from base.forms import ContatoForm
from base.forms import ReservaDeBanhoForm
from base.models import Contato

# Create your views here.
def inicio(request):
  return render(request, 'inicio.html')


def contato(request):
  print('método: ',request.method)
  sucesso = False

  form = ContatoForm(request.POST or None)
  if form.is_valid():
    form.save()
    sucesso = True

  context = {
    "nome": "fabio mariano",
    "telefone": "81 99999999",
    "form": form,
    "sucesso": sucesso
  }
  return render(request, 'contato.html', context)

def reservaDeBanho(request):
  sucesso = False

  form = ReservaDeBanhoForm(request.POST or None)
  if form.is_valid():
    form.save()
    sucesso = True

  context = {
    "form": form,
    "sucesso": sucesso
  }

  return render(request, 'reserva_de_banho.html', context)

reserva/views.py
from django.shortcuts import render
from reserva.forms import ReservaForm

# Create your views here.
def criar_reserva(request):
  form = ReservaForm(request.POST or None)
  sucesso = False

  if form.is_valid():
    form.save()
    sucesso = True

  contexto = {
    'form': form,
    'sucesso': sucesso
  }

  return render(request, 'criar_reserva_de_banho.html', contexto)

rest_api/views.py
from django.shortcuts import render
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.viewsets import ModelViewSet, ReadOnlyModelViewSet
from reserva.models import Reserva, Petshop
from base.models import Contato
from rest_api.serializers import AgendamentoSerializer, ContatoSerializer, PetshopSerializer
from rest_framework.permissions import IsAuthenticatedOrReadOnly, IsAuthenticated
from rest_framework.authentication import TokenAuthentication

class PetshopModelViewSet(ReadOnlyModelViewSet):
  queryset = Petshop.objects.all()
  serializer_class = PetshopSerializer
  permission_classes = [IsAuthenticatedOrReadOnly]
  authentication_classes = [TokenAuthentication]

class AgendamentoModelViewSet(ModelViewSet):
  queryset = Reserva.objects.all()
  serializer_class = AgendamentoSerializer
  permission_classes = [IsAuthenticatedOrReadOnly]
  authentication_classes = [TokenAuthentication]

class ContatoModelViewSet(ModelViewSet):
  queryset = Contato.objects.all()
  serializer_class = ContatoSerializer
  permission_classes = [IsAuthenticated]
  authentication_classes = [TokenAuthentication]


@api_view(['GET', 'POST'])
def hello_world(request):
  if request.method == 'POST':
    name = request.data.get('name')
    age = request.data.get('age')
    return Response({ 'message': f'Olá, {name}, seja bem-vindo! Você atualmente está com {age} anos'})

  return Response({ 'message': 'Hello World!!'})

base/templates/contato.html
<main>
  {% extends "inicio.html" %}
  {% block principal %}
    <div class="container">
      <h1 class="text-center">
        Página de contato
      </h1>
  
      <p>
        Envie uma mensagem ou entre em contato com o nosso representante: {{ nome|upper }} - {{ telefone }}
      </p>
  
      {% if sucesso %}
        <div class="alert alert-success" role="alert">
          Sua mensagem foi enviada com sucesso!
        </div>
      {% else %}
        <form method="post" novalidate>
          {% csrf_token %}
          {% load bootstrap5 %}
          {% bootstrap_form form %}
          <button type="submit" class="btn btn-primary">Enviar</button>
        </form>
      {% endif %}
    </div>
  {% endblock %}

</main>

base/templates/inicio.html
<!DOCTYPE html>
<html>
  <head>
    <title>Aula sobre DJANGO</title>
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/contato">Contato</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'reserva:criar_reserva' %}">Reserva de banho</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
              Dropdown
            </a>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled">Disabled</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

    
    {% block principal %}
      <h1>
        View de início - Django template
      </h1>
    {% endblock %}

  </body>
</html>

base/templates/reserva_de_banho.html
<main>
  {% extends "inicio.html" %}
  {% block principal %}
    <div class="container">
      <h1 class="text-center">
        Reserve o banho do seu PET
      </h1>
    
      {% if sucesso %}
        <div class="alert alert-success" role="alert">
          Reserva feita com sucesso!
        </div>
      {% else %}
        <form method="post" novalidate>
          {% csrf_token %}
          {% load bootstrap5 %}
          {% bootstrap_form form %}
          <button type="submit" class="btn btn-primary">Reservar</button>
        </form>
      {% endif %}
    </div>
  {% endblock %}

</main>

reserva/templates/criar_reserva_de_banho.html
<main>
  {% extends "inicio.html" %}
  {% block principal %}
    <div class="container">
      <h1 class="text-center">
        Reserve o banho do seu PET
      </h1>
    
      {% if sucesso %}
        <div class="alert alert-success" role="alert">
          Reserva feita com sucesso!
        </div>
      {% else %}
        <form method="post" novalidate>
          {% csrf_token %}
          {% load bootstrap5 %}
          {% bootstrap_form form %}
          <button type="submit" class="btn btn-primary">Reservar</button>
        </form>
      {% endif %}
    </div>
  {% endblock %}
</main>